# Generated by Django 4.1.1 on 2022-10-25 10:29

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pro_desc',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
