# Generated by Django 4.1.1 on 2022-10-25 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_sub_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, null=True),
        ),
    ]
