# Generated by Django 4.1.1 on 2022-10-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_main_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='after_discount',
        ),
    ]
