# Generated by Django 4.1.1 on 2022-11-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_rename_old_price_product_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_retail',
            field=models.BooleanField(default=0),
        ),
    ]
